### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lukakralik** [lukakralik/solwordle#1]
- [x] Load dataset directly by language and word length
- [x] Load guesses by color into three cases
- [x] List out all matching words by their likeness
